version: "3.8"

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - "3030:80"
    restart: on-failure
    volumes:
    - ./:/opt/node_app/app:delegated
    - ./package.json:/opt/node_app/package.json
    - ./yarn.lock:/opt/node_app/yarn.lock
    - notused:/opt/node_app/app/node_modules