services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 9080:8080
      - 9443:8443
    volumes:
      - /Container/obsidian/vaults:/vaults
      - /Container/obsidian/config:/config
    environment:
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-git
      - CUSTOM_PORT="8080"
      - CUSTOM_HTTPS_PORT="8443" 