version: '3'
service:
  vikunja:
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_SERVICE_JWTSECRET=FERGHJHJGHHFgdsf543545tfgg
      VIKUNJA_SERVICE_PUBLICURL=http://umbra.local
      VIKUNJA_DATABASE_PATH=/db/vikunja.db
    ports:
      - 3456:3456
    volumes:
      - /Container/Vikunja/files:/app/vikunja/files
      - /Container/Vikunja/db:/db
    restart: unless-stopped